apiVersion: apps/v1
kind: Deployment
metadata:
  name: kita-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kita-operator
  template:
    metadata:
      labels:
        name: kita-operator
    spec:
      serviceAccountName: kita-operator
      containers:
        - name: kita-operator
          image: danistrebel/kita-operator:latest
          command:
            - kita-operator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 50Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kita-operator"
