apiVersion: apps/v1
kind: Deployment
metadata:
  name: kita-space-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kita-space-operator
  template:
    metadata:
      labels:
        name: kita-space-operator
    spec:
      serviceAccountName: kita-space-operator
      containers:
        - name: kita-space-operator
          image: kita-space-operator:latest
          command:
          - kita-space-operator
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 50Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kita-space-operator"
